en_words = [
    "ACID properties",
    "API endpoint",
    "API gateway",
    "AVL tree",
    "AWS",
    "CNN",
    "DOM",
    "Docker",
    "ETL",
    "GitLab CI",
    "IaaS",
    "Jenkins",
    "Kubernetes",
    "MLflow",
    "MapReduce",
    "PaaS",
    "ROC curve",
    "ReLU",
    "SQL injection",
    "SSL certificate",
    "SaaS",
    "TF-IDF",
    "YOLO",
    "abstract class",
    "abstraction",
    "access control",
    "activation function",
    "adapter",
    "adapter pattern",
    "adjacency matrix",
    "aggregation",
    "alerting",
    "algebraic type",
    "anchor box",
    "anomaly detection",
    "api gateway",
    "applicative",
    "array",
    "artifact",
    "artifact repository",
    "asynchronous processing",
    "attention mechanism",
    "authentication",
    "authorization",
    "auto scaling",
    "automated monitoring",
    "automated testing",
    "availability zone",
    "background job",
    "backpressure",
    "backpropagation",
    "backtracking",
    "backup",
    "bag of words",
    "bagging",
    "balanced tree",
    "baseline model",
    "batch",
    "batch inference",
    "batch normalization",
    "batch processing",
    "bias",
    "bias-variance tradeoff",
    "binary heap",
    "binary search",
    "binary search tree",
    "binary tree",
    "blue-green deployment",
    "bottleneck",
    "bounded context",
    "bounding box",
    "branch strategy",
    "breadth-first search",
    "bridge pattern",
    "browser cache",
    "brute force attack",
    "bubble sort",
    "build",
    "build agent",
    "build trigger",
    "builder pattern",
    "bulkhead pattern",
    "bundling",
    "caching",
    "canary deployment",
    "capacity planning",
    "chain of responsibility",
    "chaining",
    "checkpoint",
    "circuit breaker",
    "circular buffer",
    "class",
    "classification",
    "clean architecture",
    "clickjacking",
    "closure",
    "cloud computing",
    "cloud cost optimization",
    "cloud migration",
    "cloud monitoring",
    "cloud native",
    "cloud provider",
    "cloud security",
    "cloud storage",
    "cluster",
    "clustering",
    "code coverage",
    "code splitting",
    "collation",
    "collision",
    "command",
    "command pattern",
    "command query separation",
    "commit",
    "complexity",
    "component",
    "composite pattern",
    "composition",
    "concept drift",
    "concurrent processing",
    "config map",
    "configuration management",
    "confusion matrix",
    "connection pooling",
    "consensus",
    "consistency",
    "constraint",
    "constructor",
    "container",
    "container registry",
    "container runtime",
    "content delivery network",
    "content security policy",
    "continuation",
    "continuous delivery",
    "continuous integration",
    "convolution",
    "coreference resolution",
    "corpus",
    "cross-origin resource sharing",
    "cross-site request forgery",
    "cross-site scripting",
    "cross-validation",
    "currying",
    "cursor",
    "daemon set",
    "data aggregation",
    "data anonymization",
    "data catalog",
    "data cleaning",
    "data compression",
    "data deduplication",
    "data drift",
    "data encryption",
    "data enrichment",
    "data fabric",
    "data federation",
    "data filtering",
    "data governance",
    "data ingestion",
    "data integration",
    "data lake",
    "data lineage",
    "data locality",
    "data mart",
    "data masking",
    "data mesh",
    "data migration",
    "data normalization",
    "data observability",
    "data orchestration",
    "data parsing",
    "data partitioning",
    "data pipeline",
    "data processing",
    "data profiling",
    "data quality",
    "data quality monitoring",
    "data reconciliation",
    "data replication",
    "data sampling",
    "data schema",
    "data serialization",
    "data sharding",
    "data shuffling",
    "data skew",
    "data standardization",
    "data transformation",
    "data validation",
    "data versioning",
    "data virtualization",
    "data warehouse",
    "data wrangling",
    "database index",
    "database migration",
    "database schema",
    "deadlock",
    "decision tree",
    "decoder",
    "decorator",
    "decorator pattern",
    "deep network",
    "denormalization",
    "dense layer",
    "dependency injection",
    "dependency management",
    "dependency parsing",
    "deployment",
    "deployment environment",
    "deployment pipeline",
    "deployment strategy",
    "depth-first search",
    "deque",
    "destructor",
    "dimensionality reduction",
    "directory traversal",
    "disaster recovery",
    "distributed computing",
    "distributed tracing",
    "divide and conquer",
    "docker compose",
    "dockerfile",
    "domain-driven design",
    "doubly linked list",
    "dropout",
    "dynamic programming",
    "edge",
    "edge detection",
    "elasticity",
    "embedding",
    "encapsulation",
    "encoder",
    "encryption",
    "ensemble",
    "epoch",
    "error handling",
    "event sourcing",
    "event-driven architecture",
    "eventual consistency",
    "experiment configuration",
    "experiment logging",
    "experiment metadata",
    "experiment pipeline",
    "experiment run",
    "experiment tracking",
    "experiment tracking system",
    "experiment visualization",
    "experiment workflow",
    "f1-score",
    "facade",
    "face recognition",
    "factory method",
    "factory pattern",
    "failover",
    "fault tolerance",
    "feature",
    "feature engineering",
    "feature extraction",
    "feature flag",
    "feature map",
    "feature pyramid",
    "feature selection",
    "feedforward",
    "fibonacci heap",
    "filter",
    "firewall",
    "first-class function",
    "flyweight pattern",
    "fold",
    "foreign key",
    "functor",
    "generator",
    "graceful shutdown",
    "gradient boosting",
    "gradient descent",
    "graph",
    "greedy algorithm",
    "grid search",
    "hash table",
    "hashing",
    "health check",
    "heap",
    "heap sort",
    "helm",
    "hexagonal architecture",
    "high availability",
    "higher-order function",
    "horizontal scaling",
    "hot module replacement",
    "hybrid cloud",
    "hydration",
    "hyperparameter",
    "hyperparameter optimization",
    "hyperparameter tuning",
    "idempotency",
    "identity and access management",
    "image",
    "image augmentation",
    "image classification",
    "image enhancement",
    "image preprocessing",
    "image processing",
    "image reconstruction",
    "image registration",
    "immutability",
    "incident response",
    "inference",
    "infrastructure as code",
    "infrastructure automation",
    "ingress",
    "inheritance",
    "insertion sort",
    "instance segmentation",
    "integration testing",
    "interface",
    "internationalization",
    "isolation level",
    "iteration",
    "iterator",
    "iterator pattern",
    "k-means",
    "kernel",
    "label",
    "lambda",
    "language model",
    "latency",
    "layer",
    "layered architecture",
    "lazy evaluation",
    "lazy loading",
    "learning rate",
    "lemmatization",
    "linked list",
    "load balancer",
    "load balancing",
    "localization",
    "logging",
    "loss function",
    "machine translation",
    "man-in-the-middle",
    "managed service",
    "map",
    "materialized view",
    "mediator",
    "mediator pattern",
    "memoization",
    "merge conflict",
    "merge sort",
    "message queue",
    "method",
    "metrics tracking",
    "microservice",
    "middleware",
    "model artifact",
    "model auditing",
    "model checkpoint",
    "model comparison",
    "model compression",
    "model containerization",
    "model debugging",
    "model deployment",
    "model diagnostics",
    "model distillation",
    "model drift",
    "model endpoint",
    "model evaluation",
    "model feedback",
    "model governance",
    "model health",
    "model health check",
    "model iteration",
    "model latency",
    "model load balancing",
    "model logging",
    "model maintenance",
    "model metrics",
    "model monitoring",
    "model observability",
    "model optimization",
    "model orchestration",
    "model pipeline",
    "model pruning",
    "model quantization",
    "model registry",
    "model reliability",
    "model retraining",
    "model rollback",
    "model scaling",
    "model selection",
    "model serialization",
    "model serving",
    "model testing",
    "model throughput",
    "model validation",
    "model versioning",
    "model-view-controller",
    "monad",
    "monitoring dashboard",
    "multi-cloud",
    "n-gram",
    "named entity",
    "named entity recognition",
    "namespace",
    "neural network",
    "neuron",
    "node",
    "normalization",
    "object",
    "object detection",
    "object tracking",
    "observer",
    "observer pattern",
    "onion architecture",
    "optical flow",
    "optimizer",
    "orchestration",
    "outlier",
    "overfitting",
    "overload",
    "override",
    "padding",
    "parameter sweep",
    "parsing",
    "part of speech",
    "partial application",
    "partition",
    "partition tolerance",
    "pattern matching",
    "penetration testing",
    "performance baseline",
    "performance degradation",
    "performance metrics",
    "performance monitoring",
    "performance optimization",
    "persistent volume",
    "pipeline",
    "pixel",
    "pod",
    "pod disruption budget",
    "pointer",
    "polyfill",
    "polyglot persistence",
    "polymorphism",
    "pooling",
    "pooling layer",
    "pose estimation",
    "precision",
    "predicate",
    "prediction monitoring",
    "primary key",
    "priority queue",
    "probing",
    "production",
    "progressive enhancement",
    "progressive web application",
    "property",
    "prototype",
    "proxy",
    "proxy pattern",
    "publish-subscribe",
    "pure function",
    "query optimization",
    "queue",
    "quick sort",
    "random forest",
    "random search",
    "rate limiting",
    "reactive programming",
    "real-time inference",
    "recall",
    "recovery",
    "recursion",
    "red-black tree",
    "reduce",
    "redundancy",
    "referential transparency",
    "region",
    "regression",
    "regularization",
    "release management",
    "replica set",
    "replication",
    "repository pattern",
    "reproducibility",
    "request handling",
    "request throttling",
    "resource allocation",
    "resource provisioning",
    "response formatting",
    "responsive design",
    "role-based access control",
    "rollback",
    "rolling update",
    "routing",
    "saga pattern",
    "sanitization",
    "savepoint",
    "scalability",
    "scaling",
    "secret",
    "security audit",
    "security breach",
    "security compliance",
    "security header",
    "security incident",
    "security misconfiguration",
    "security monitoring",
    "security patch",
    "security token",
    "security token service",
    "segmentation",
    "selection sort",
    "self-attention",
    "semantic segmentation",
    "sentiment analysis",
    "sequence-to-sequence",
    "serialization",
    "server-sent events",
    "server-side rendering",
    "serverless",
    "service",
    "service autonomy",
    "service boundary",
    "service choreography",
    "service configuration",
    "service contract",
    "service decomposition",
    "service deployment",
    "service discovery",
    "service idempotency",
    "service isolation",
    "service level agreement",
    "service logging",
    "service mesh",
    "service monitoring",
    "service orchestration",
    "service registry",
    "service resilience",
    "service scaling",
    "service telemetry",
    "service versioning",
    "service worker",
    "session hijacking",
    "session management",
    "shadow DOM",
    "shadow deployment",
    "sharding",
    "shortest path",
    "side effect",
    "sidecar pattern",
    "sigmoid",
    "single page application",
    "singleton",
    "singleton pattern",
    "skip list",
    "softmax",
    "sorting",
    "spanning tree",
    "stack",
    "stacking",
    "staging",
    "state",
    "state management",
    "state pattern",
    "statefulset",
    "static site generation",
    "statistical monitoring",
    "stemming",
    "stop word",
    "stored procedure",
    "strategy",
    "strategy pattern",
    "stream processing",
    "stride",
    "support vector machine",
    "system monitoring",
    "tablespace",
    "tail recursion",
    "tanh",
    "template method",
    "tensor",
    "test automation",
    "text classification",
    "text mining",
    "text summarization",
    "threat modeling",
    "threshold monitoring",
    "throttling",
    "throughput",
    "tokenization",
    "topological sort",
    "transaction",
    "transfer learning",
    "transformer",
    "transpiling",
    "traversal",
    "tree shaking",
    "trie",
    "trigger",
    "two-factor authentication",
    "type inference",
    "underfitting",
    "union find",
    "unit testing",
    "user interface",
    "vacuum",
    "validation",
    "version control",
    "vertex",
    "vertical scaling",
    "view",
    "virtual DOM",
    "virtual machine",
    "virtualization",
    "visitor pattern",
    "vocabulary",
    "volume",
    "vulnerability scanning",
    "web accessibility",
    "web components",
    "web manifest",
    "webhook",
    "websocket",
    "weight",
    "word embedding",
    "word segmentation",
    "word sense disambiguation",
    "zero-day exploit",
]